variables:
  BUILDEVENT_FILE: "../buildevents.txt"
  PACT_CLI_IMG: pactfoundation/pact-cli:0.12.3.0
  PACT_BROKER_URL: pact:9292

stages:
  - build

build-job:
  stage: build

  image: docker:20.10.16

  services:
    - name: postgres:9.6.19-alpine
      alias: postgres
    - name: pactfoundation/pact-broker:2.59.2.0
      alias: pact

  script:
    - echo ${PACT_BROKER_URL}
    - curl -I ${PACT_BROKER_URL}
