variables:
  BUILDEVENT_FILE: "../buildevents.txt"
  PACT_CLI_IMG: pactfoundation/pact-cli:0.12.3.0
  PACT_BROKER_URL: pact:9292

stages:
  - build

build-job:
  stage: build

  image: docker:20.10.16

  services:
    - name: postgres:9.6.19-alpine
      alias: postgres
      variables:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    - name: pactfoundation/pact-broker:2.59.2.0
      alias: pact
      variables:
        - PACT_BROKER_DATABASE_HOST=postgres
        - PACT_BROKER_DATABASE_USERNAME=postgres
        - PACT_BROKER_DATABASE_PASSWORD=postgres
        - PACT_BROKER_BASIC_AUTH_USERNAME=rw_user
        - PACT_BROKER_BASIC_AUTH_PASSWORD=rw_pass
        - PACT_BROKER_BASIC_AUTH_READ_ONLY_USERNAME=ro_user
        - PACT_BROKER_BASIC_AUTH_READ_ONLY_PASSWORD=ro_pass

  script:
    - echo ${PACT_BROKER_URL}
    - curl -I ${PACT_BROKER_URL}
