version: 2.1

orbs:
  buildevents: honeycombio/buildevents@0.8.0
  docker: circleci/docker@2.1.3
  maven: circleci/maven@1.3.0

commands:

  envvars:
    steps:
      - run: echo ${BUILDEVENTS_SPAN_ID}

  install-xpath:
    steps:
      - run: |
          buildevents cmd ${CIRCLE_WORKFLOW_ID} ${BUILDEVENTS_SPAN_ID} 'apt update' -- \
            sudo apt update
      - run: |
          buildevents cmd ${CIRCLE_WORKFLOW_ID} ${BUILDEVENTS_SPAN_ID} 'install xpath' -- \
            sudo apt install libxml-xpath-perl
  
  service-build:
    parameters:
      service:
        type: string

    steps:
      - run: ./.circleci/scripts/<< parameters.service >>-build.sh
      - run:
          name: add test results to span
          # This is a workaround for `buildevents/add_context` not allowing a `when`
          when: always
          command: |
            FS_COMPLETED=$(xpath -q -e 'failsafe-summary/completed/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)
            FS_ERRORS=$(xpath -q -e 'failsafe-summary/errors/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)
            FS_FAILURES=$(xpath -q -e 'failsafe-summary/failures/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)
            FS_SKIPPED=$(xpath -q -e 'failsafe-summary/skipped/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)
            echo " ci.reporting.integration.completed=${FS_COMPLETED}" >> /tmp/buildevents/extra_fields.lgfmt
            echo " ci.reporting.integration.errors=${FS_ERRORS}" >> /tmp/buildevents/extra_fields.lgfmt
            echo " ci.reporting.integration.failures=${FS_FAILURES}" >> /tmp/buildevents/extra_fields.lgfmt
            echo " ci.reporting.integration.skipped=${FS_SKIPPED}" >> /tmp/buildevents/extra_fields.lgfmt

jobs:

  setup:
    docker:
      - image: cimg/go:1.18

    steps:
      - buildevents/start_trace

  watch:
    docker:
      - image: cimg/go:1.18

    steps:
      - buildevents/watch_build_and_finish

  service_build:
    machine:
      image: ubuntu-2204:2022.04.2

    environment:
      PACT_CLI_IMG: pactfoundation/pact-cli:0.12.3.0
      PACT_BROKER_URL: localhost:9292
    
    parameters:
      service:
        type: string

    steps:
      - buildevents/with_job_span:
          steps:
            - checkout
            
            - run:
                command: |
                  BUILDEVENTS_SPAN_ID=$(echo ${CIRCLE_JOB}-${CIRCLE_NODE_INDEX} | sha256sum | awk '{print $1}')
                  echo "export BUILDEVENTS_SPAN_ID=\"${BUILDEVENTS_SPAN_ID}\"" >> $BASH_ENV
                  echo $BUILDEVENTS_SPAN_ID

            - envvars

            - install-xpath

            - run:
                name: Start dependencies with docker-compose
                command: |
                  export BUILDEVENTS_SPAN_ID=$(echo ${CIRCLE_JOB}-${CIRCLE_NODE_INDEX} | sha256sum | awk '{print $1}')
                  buildevents cmd ${CIRCLE_WORKFLOW_ID} ${BUILDEVENTS_SPAN_ID} 'run dependencies' -- \
                    docker-compose -f pact-tools/pact-broker/docker-compose.yml up
                background: true

            - service-build:
                service: << parameters.service >>

            - run:
                name: Stop dependencies with docker-compose
                command: |
                  BUILDEVENTS_SPAN_ID=$(echo ${CIRCLE_JOB}-${CIRCLE_NODE_INDEX} | sha256sum | awk '{print $1}')
                  buildevents cmd ${CIRCLE_WORKFLOW_ID} ${BUILDEVENTS_SPAN_ID} 'clean up dependencies' -- \
                    docker-compose -f pact-tools/pact-broker/docker-compose.yml down
                when: always

workflows:
  build_and_test:
    when: ${CIRCLE_BRANCH}=="circleci"
    jobs:
      - setup
      - watch:
          requires:
            - setup
      - service_build:
          requires:
            - setup
          matrix:
            parameters:
              service: [
                "credit-score-service",
                "special-membership-service",
                "welcome-member-email-service",
              ]
