version: 2.1

orbs:
  buildevents: honeycombio/buildevents@0.7.1
  docker: circleci/docker@2.1.3
  maven: circleci/maven@1.3.0

executors:
  linuxgo:
    docker:
      - image: cimg/go:1.18
  
  java:
    docker:
      - image: cimg/openjdk:14.0

commands:

  install-xpath:
    steps:
      - run: sudo apt update
      - run: sudo apt install libxml-xpath-perl
  
  service-build:
    parameters:
      service:
        type: string

    steps:
      - run: ./.circleci/scripts/<< parameters.service >>-build.sh
      - buildevents/add_context:
          field_name: ci.reporting.integration.completed
          field_value: $(xpath -q -e 'failsafe-summary/completed/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)]
      - buildevents/add_context:
          field_name: ci.reporting.integration.errors
          field_value: $(xpath -q -e 'failsafe-summary/errors/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)
      - buildevents/add_context:
          field_name: ci.reporting.integration.failures
          field_value: $(xpath -q -e 'failsafe-summary/failures/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)
      - buildevents/add_context:
          field_name: ci.reporting.integration.skipped
          field_value: $(xpath -q -e 'failsafe-summary/skipped/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)
      - run: cat /tmp/buildevents/extra_fields.lgfmt


jobs:

  setup:
    executor: linuxgo
    steps:
      - buildevents/start_trace

  watch:
    executor: linuxgo
    steps:
      - buildevents/watch_build_and_finish

  build:
    executor: java

    environment:
      PACT_CLI_IMG: pactfoundation/pact-cli:0.12.3.0
      PACT_BROKER_URL: localhost:9292
    
    parameters:
      service:
        type: string

    steps:
      - buildevents/with_job_span:
          steps:
            - checkout
            
            - install-xpath

            - setup_remote_docker:
                version: 20.10.14
                docker_layer_caching: true

            - run:
                name: Start dependencies with docker-compose
                command: |
                  docker-compose -f pact-tools/pact-broker/docker-compose.yml up -d
                background: true

            - service-build:
                service: << parameters.service >>

            - run:
                name: Stop dependencies with docker-compose
                command: docker-compose -f pact-tools/pact-broker/docker-compose.yml down
                when: always


workflows:
  build_and_test:
    jobs:
      - setup
      - watch:
          requires:
            - setup
      - build:
          requires:
            - setup
          matrix:
            parameters:
              service: [
                "credit-score-service",
                "special-membership-service",
                "welcome-member-email-service",
              ]
